# Generated by Django 6.1.1 on 2026-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0002_alter_qr_code_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code'),
        ),
    ]
